# Generated by Django 5.2.1 on 2025-06-03 12:06

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=chats.models.chat_pic_path),
        ),
    ]
