# Generated by Django 5.2.1 on 2025-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
