# Generated by Django 5.2 on 2025-05-02 04:36

import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('time_stamp', models.DateTimeField(auto_created=True)),
                ('message_id', models.BigIntegerField(default=users.utils.generate_random_bigint, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('is_file', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('unique_id', models.BigIntegerField(default=users.utils.generate_random_bigint, editable=False, primary_key=True, serialize=False)),
                ('is_delivered', models.BooleanField()),
                ('is_read', models.BooleanField()),
                ('delivered_at', models.DateTimeField()),
                ('read_at', models.DateTimeField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_messages.message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
