# Generated by Django 5.2 on 2025-05-22 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_country_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\+[0-9]{1,4}$', message='Country code must be 1–4 digits, prefixed with +')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(help_text="E.g. '+1', '91'", max_length=4, validators=[django.core.validators.RegexValidator('^\\+[0-9]{1,4}$', message='Country code must be 1–4 digits, prefixed with +')]),
        ),
    ]
